import { describe, expect, it } from "vitest";
import { execFileSync } from "node:child_process";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

const BIN = path.resolve(__dirname, "../bin/generate-clients.mjs");
const APP_ID = "22222222-2222-2222-2222-222222222222";

function project() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "app-client-"));
  fs.mkdirSync(path.join(dir, "clients"));
  // A resource-client file the merged index must keep.
  fs.writeFileSync(
    path.join(dir, "clients", "db.ts"),
    "// DO NOT EDIT - Auto-generated by @major-tech/resource-client\nexport const dbClient = 1;\n",
  );
  return dir;
}

const run = (dir, ...args) => execFileSync("node", [BIN, ...args], { cwd: dir, encoding: "utf-8" });

describe("major-app-client", () => {
  it("add writes a createAppFetch file with the baked id and keeps other clients in the index", () => {
    const dir = project();

    run(dir, "add", APP_ID, "Order Service", "--framework", "nextjs");

    const file = fs.readFileSync(path.join(dir, "clients", "orderService.ts"), "utf-8");
    expect(file).toContain("import { createAppFetch } from '@major-tech/app-client/next';");
    expect(file).toContain(`appId: '${APP_ID}'`);
    expect(file).toContain("Auto-generated by @major-tech/app-client");
    expect(file).toContain("export const orderServiceFetch = createAppFetch(");

    const index = fs.readFileSync(path.join(dir, "clients", "index.ts"), "utf-8");
    expect(index).toContain("export { dbClient } from './db';");
    expect(index).toContain("export { orderServiceFetch } from './orderService';");
    expect(JSON.parse(fs.readFileSync(path.join(dir, "apps.json"), "utf-8"))).toEqual([
      { id: APP_ID, name: "Order Service", description: "Order Service" },
    ]);
  });

  it("vite imports the root entry and reads import.meta.env", () => {
    const dir = project();

    run(dir, "add", APP_ID, "orders", "--framework", "vite");

    const file = fs.readFileSync(path.join(dir, "clients", "orders.ts"), "utf-8");
    expect(file).toContain("from '@major-tech/app-client';");
    expect(file).toContain("import.meta.env.MAJOR_JWT_TOKEN");
    expect(file).not.toContain("server-only");
  });

  it("remove deletes the file and the registry entry", () => {
    const dir = project();
    run(dir, "add", APP_ID, "orders", "--framework", "nextjs");

    run(dir, "remove", "orders", "--framework", "nextjs");

    expect(fs.existsSync(path.join(dir, "clients", "orders.ts"))).toBe(false);
    expect(JSON.parse(fs.readFileSync(path.join(dir, "apps.json"), "utf-8"))).toEqual([]);
    expect(fs.readFileSync(path.join(dir, "clients", "index.ts"), "utf-8")).not.toContain("orders");
  });
});
