import { build } from "esbuild";
import { readdir } from "fs/promises";
import { join } from "path";

// Find all .js files in dist (generated by tsc)
async function findJsFiles(dir, files = []) {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      await findJsFiles(fullPath, files);
    } else if (entry.name.endsWith(".js")) {
      files.push(fullPath);
    }
  }
  return files;
}

const jsFiles = await findJsFiles("dist");

const common = {
  bundle: false, // Don't bundle - keep as separate files
  platform: "neutral",
  target: "es2022",
  sourcemap: true,
  minify: false,
  keepNames: true,
};

// Convert each .js file to .cjs for CommonJS support
await Promise.all(
  jsFiles.map((file) =>
    build({
      ...common,
      entryPoints: [file],
      format: "cjs",
      outfile: file.replace(/\.js$/, ".cjs"),
    })
  )
);

console.log(`✅ Built ${jsFiles.length} files (ESM + CJS)`);

